#!/usr/bin/env bash

set -eu

if [ -z "${SYSLOG_WWW}" ]; then
    echo "Please point the SYSLOG_WWW environment variable to the podcast website to be uploaded."
    exit 1
fi

if [ $# -ne 3 ]; then
    echo "Usage: $0 user password host"
    exit 1
fi

USER=$1
PASS=$2
HOST=$3

echo ">> Uploading to $HOST..."
lftp -e "mirror -R  --transfer-all --scan-all-first ${SYSLOG_WWW} public_html" -u "$USER","$PASS" "$HOST"
echo ">> Upload done!"
